### ISSUE TITLE
nice going retard

### ISSUE THREAD

**Issue by swoopae** [KittenPopo/Titanfall2_Offsets#1]
https://github.com/KittenPopo/Titanfall2_Offsets/tree/7d23bfe90abadeb43bf8877891348b25bc2ef638
mf can't even figure out how to use git LMAO
also "stop ruining titanfall 2" stop coping moron noone cares

**Comment by KittenPopo** [comment]
yea i understand how commits work, i was planning to add thousands of more sigs
and titanfall is fun you should try it
